# Issues must have some content
blank_issues_enabled: false

# Contact links
contact_links:
  - name: "stealthscale Discord community"
    url: "https://discord.gg/c84AZQhmpx"
    about: "Please ask and answer questions about usage of stealthscale here."
  - name: "stealthscale usage documentation"
    url: "https://stealthscale.net/"
    about: "Find documentation about how to configure and run stealthscale."
