#!/bin/sh
# postrm script for the coordination service.

set -e

# Summary of how this script can be called:
#        * <postrm> 'remove'
#        * <postrm> 'purge'
#        * <old-postrm> 'upgrade' <new-version>
#        * <new-postrm> 'failed-upgrade' <old-version>
#        * <new-postrm> 'abort-install'
#        * <new-postrm> 'abort-install' <old-version>
#        * <new-postrm> 'abort-upgrade' <old-version>
#        * <disappearer's-postrm> 'disappear' <overwriter>
#          <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package.


case "$1" in
    remove)
      if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
      fi
    ;;

    purge)
      userdel stealthscale || true
      # Remove both old and new data dirs on purge (old coordination for backward compat)
      rm -rf /var/lib/stealthscale
      rm -rf /var/lib/coordination
      if id -u coordination >/dev/null 2>&1; then userdel coordination || true; fi
      if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge stealthscale.service >/dev/null || true
      fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac
